#let qed = {h(1fr); sym.wj; sym.space.nobreak; $qed$}
I assume knowledge of the definition of a Lie group.

Proposition 1. Every Lie group homomorphism has constant rank.

_Proof_. Let $F: G arrow H$ be a Lie group homomorphism, and let $e$ and $tilde(e)$ be the identities of $G$ and $H$, respectively. Take $g_0 in G$ and consider $d F_(g_0)$ and $d F_e$.
Since $F$ is a homomorphism, for all $g in G$, $F(L_(g_0) (g)) = F(g_0 g) = F(g_0) F(g) = L_F(g_0) (F(g))$. That is, $F compose L_g_0 = L_(F(g_0)) compose F$. Then taking differentials at $e$ gives $d F_(g_0) compose d (L_g_0)_e = d (L_F(g_0))_(tilde(e)) compose d F_e$. The differentials involving $L$ are isomorphisms, as $L$ is a diffeomorphism. So $d F_(g_0)$ and $d F_e$ have the same rank. #qed

Corollary. Bijective Lie group homomorphisms are diffeomorphisms.

This follows from the rank theorem. 

Theorem 2. Let $G$ be a  connected Lie group. Then there exists a simply connected Lie group termed the universal covering group of $G$ such that there exists a smooth covering map and Lie group homomorphism $pi: tilde(G) arrow G$.

Recall that a smooth covering map is a surjective map which evenly covers its image by mapping sections diffeomorphically.

_Proof sketch_. Consider the multiplication and inversion maps on $G$, which we term $m$ and $i$. Choose $tilde(e) in pi^(-1) (e)$. Now, since $tilde(G)$ is simply connected, we have a unique and continuous lift of $m compose (pi times pi): tilde(G) times tilde(G) arrow G$ to $tilde(m): tilde(G) times tilde(G) arrow tilde(G)$, with $tilde(m)(tilde(e), tilde(e)) = tilde(e)$. Since $pi$ is a local diffeomorphism (in particular smooth) and $pi compose tilde(m) = m compose (pi times pi)$ is smooth, so is $tilde(m)$. For the same reason, we have a smooth lift of $i$ to $tilde(i): tilde(G) arrow tilde(G)$ such that $tilde(i)(tilde(e)) = tilde(e)$ and $pi compose tilde(i) = i compose pi$. We use these to define multiplication and inversion in $tilde(G)$. Now it suffices to show that $tilde(G)$ is a group, since its operations are already smooth and $pi$ is a homomorphism by definition.

We will show identity and invertibility. Let $f: tilde(G) arrow tilde(G)$ be defined by $f(x) = tilde(e)(x)$. Then $pi compose f(x) = pi(tilde(e)) pi(x)=pi(x)$, so $f$ is a lift of $pi$. $id_(tilde(G))$ is also a lift of $pi$, and $f$ and $id_tilde(G)$ agree at a point, since $f(tilde(e)) = tilde(m)(tilde(e),tilde(e))=tilde(e)$. Now, we must show that $tilde(i)(x)x = x tilde(i)(x) = tilde(e)$ for all $x in tilde(G)$. Let $g: hat(G) arrow hat(G)$ be defined by $g(x) = tilde(i)(x) x$ (right-multiplication follows a similar argument from here). Since $pi compose g(x) = pi(tilde(i)(x)x)=pi(tilde(i)(x))pi(x) = pi(x)^(-1) pi(x) = e$, $g$ is a lift of the constant map to $e$ on $G$. One lift of this constant map is $g'(x) = tilde(e)$, and $g$ and $g'$ agree at $tilde(e)$ by the defining property of $g$, so $g=g'$ by the unique lifting property of covering maps. #qed

Proposition 3. The universal covering group of $G$ described in Theorem 1 is unique up to isomorphism, in the sense that for any two universal covering groups $G', G''$ of $G$, there is a Lie group isomorphism $Phi: G' arrow G''$ such that the projections $pi, pi'$ corresponding to $G'$ and $G''$ satisfy $pi = pi' compose Phi$.

Definition. A Lie subgroup of $G$ is a subgroup of $G$ such that there is a topology and smooth structure making the subgroup a Lie group and an immersed submanifold.

Proposition 4. Let $G$ be a Lie group with $H subset.eq G$ being a subgroup which is an embedded submanifold. Then $H$ is a Lie subgroup.

_Proof_. Because multiplication on $G$ is smooth, its restriction to $H^2$ is also smooth. The image of this restricted map is contained within $H$, and by the note following Proposition 14 in Chapter 5, that map is smooth. Similarly, inversion is smooth on $H$. So $H$ is a Lie subgroup. #qed

Proposition 5. Suppose $G$ is a Lie group and $H$ is an open subgroup. Then $H$ is an embedded Lie group, and $H$ is closed.

_Proof_. $H$ is embedded in $G$ by Proposition 1 of Chapter 5. Because $L_g$ is a diffeomorphism, the cosets of $H$ are also open. So $G\\H$ is a union of open sets, so $H$ is closed.

Proposition 6. Suppose $G$ is a Lie group, and $W subset.eq G$ is any neighborhood of the identity.
#set enum(numbering: "(a)")

+ $W$ generates an open subgroup of $G$.
+ If $W$ is connected, $W$ generates a connected group.
+ If $G$ is connected, then $W$ generates $G$.

_Proof_. Let $H$ be the group generated by $W$. For each $k in NN$, let $W_k$ be the set of elements of $G$ which are products of $k$ or fewer elements of $W union W^(-1)$. $H$ is the union of all the $W_k$'s, as every element of $H$ is a finite product of elements in $W union W^(-1)$. Also, $W^(-1)$ is open, as inversion is a diffeomorphism. So $W_1 := W union W^(-1)$ is open. $W_k$ is also open, since for each $k>1$, $W_k = W_1 W_(k-1) = union.big_(g in W_1) L_g (W_(k-1))$ is the union of images of an open set (by a suitable induction hypothesis) under some diffeomorphisms. So $H$ is open.

 Suppose $W$ is connected. $W^(-1)$ is also connected because it is the image of $W$ under a diffeomorphism, and $W_1$ is connected because $W$ and $W^(-1)$ share the identity. Since left multiplication by a point is a continuous map, successive $W_k$'s are connected because $W_1$ is connected, $W_k = W_1 W_(k-1)$ always contains the identity, and connectedness is preserved by continuity. Since each of these connected sets contain the identity, $H$ is connected. 
 
 Now, suppose $G$ is connected. Since $H$ is open and nonempty (it contains the identity), it is clopen, so $H=G$. #qed

The connected component of a Lie group $G$ that contains the identity is termed the identity component of $G$.

 Proposition 7. The identity component of a Lie group is a normal subgroup and is the only connected open subgroup. In addition, connected components of $G$ are diffeomorphic to the identity component.

Proposition 8. Let $F: G arrow H$ be a Lie group homomorphism. The kernel of $F$ is a properly embedded Lie subgroup of $G$ with codimension equal to $"rank" F$.

_Proof_. Since $F$ has constant rank, its kernel is a properly embedded submanifold of $G$ with codimension $"rank" F$ by Proposition 6 of Chapter 5. This kernel is a subgroup of $G$, so it is also a Lie group by Proposition 4. #qed

Proposition 9. Let $F: G arrow H$ be an injective Lie group homomorphism. Then $F(G)$ has a unique manifold structure making it a Lie subgroup of $H$ and $F$ a Lie group isomorphism onto $F(G)$.

_Proof_. Since $F$ is of constant rank, it is a smooth immersion by the global rank theorem. By Proposition 9 of Chapter 5, $F(G)$ has a unique manifold structure such that $F(G)$ is a smooth submanifold of $H$ and such that $F$ is a diffeomorphism onto its image. Also, $F(G)$ is a subgroup of $H$ and is a Lie group because $G$ is, so $F(G)$ is a Lie subgroup of $H$. Since $F: G arrow F(G)$ is both a group isomorphism and a diffeomorphism, it is a Lie group isomorphism.

Theorem 10. Suppose $G$ is a Lie group and $H subset.eq G$ is a Lie subgroup. Then $H$ is closed in $G$ iff $H$ is embedded.

_Proof sketch_. ($arrow.double.l$) Take a limit point of $H$ and a sequence in $H$ converging to it. Let $U$ be the domain of a slice chart for $H$ which contains the identity, and take an open $W subset.eq U$ such that $e in W$ and $overline(W) subset.eq U$. Now there is a neighborhood $V$ of $e$ such that if $g_1,g_2 in V$, $g_1 g_2^(-1) in W$. Since $h_i g^(-1) arrow e$, we can take a subsequence of this sequence which is contained in $V$ and reindex. Then $h_i h_j^(-1) = (h_i g^(-1))(h_j g^(-1))^(-1) in W$ for all $i$ and $j$, and as $i arrow infinity$ with $j$ fixed, we have that $h_i h_j^(-1) arrow g h_j^(-1) in overline(W) subset.eq U$. Since $U$ is a slice domain, $H inter U$ is a slice which is closed in $U$. So $g h_j^(-1) in H$ as well, so $g in H$. So $H$ is closed.

($arrow.double$) Since the statement follows easily if $dim H = dim G$, assume that $dim H < dim G$. Given $h_1 in H$, we want to find a neighborhood slice domain $U_1$ of $h_1$ in $G$ such that $H inter U_1$ is an embedded submanifold of $U_1$; for then some other point of $H$ can be contained in an embedded submanifold of another slice domain $U'_1$ which is of the form $R_(h h_1^-1) (U_1)$ by an appropriate right translation by an element in $H$ (which is a diffeomorphism). Then the local slice criterion will show that $H$ is an embedded submanifold of $G$.

We can take a local neighborhood around $e in H$ and a slice chart $(U, phi)$ for $V$ in $G$ centered at $e$. We can shrink $U$ to reduce to the coordinate cube case, and then $U inter V$ has the coordinate form $x^1,...,x^dim(H),0,...,0)$. We can then take $S$ to be the perpendicular slice in $U$. $S$ is a submanifold of $U$ and $G$, and $T_e V plus.o T_e S = T_e G$. The map $psi: V times S arrow G$ is defined as the restriction of $G$'s multiplication. $d psi_(e,e)$ is bijective, since the derivative sends $(X,0)$ to $X$ when $X in T_e V$ and $(0, Y)$ to $Y$ when $Y in T_e S$, which in turn follows from the unit properties of group multiplication. Now we may use the Inverse Function Theorem to get a neighborhood $W_0$ of $(e,e) in V times S$ and $U_0$ of $e in G$ such that $psi: W_0 arrow U_0$ is a diffeomorphism. We can shrink neighborhoods so that $W_0 = V_0 times S_0$, where $V_0$ and $S_0$ are neighborhoods of $e$ in $V$ and $S$, respectively. 

Let $K:= S_0 inter H$. To show that $psi(V_0 times K) = H inter U_0$, take an element $(v,s) in V_0 times S_0$. Since $V_0 subset.eq H$, $v s in H$ iff $s in H$. That is, $psi(v,s) in H inter U_0$ iff $(v,s) in V_0 times K$, since $psi$ sends subsets of $V_0 times S_0$ to $U_0$. To show that $K$ is discrete with respect to $H$'s topology, suppose $h in K$. $R_h$ is a diffeomorphism of $H$ which takes $e$ to $h$ and $V_0$ to a neighborhood $V_h subset.eq H$ of $h$. Also, $V_h = psi(V_0 times {h})$, and $K = psi({e} times K)$. $psi$ is injective on $V_0 times S_0$, so $V_h inter K = psi({e} times {h}) = {h}$. So each point of $K$ is isolated in $H$.

Now, since $K$ is discrete and a subset of $H$, it is countable, and since $H$ is closed in $G$, $K=S_0 inter H$ is closed in $S_0$. Now, some topology fact from the appendix allows us to find an isolated point $h_1$ in $K$ relative to $S_0$. So there is a neighborhood $S_1$ of $h_1$ in $S_0$ such that $S_1 inter H = h_1$. Then $U_1 := psi(V_0 times S_1)$ is a neighborhood of $h_1 in G$ such that $U_1 inter H$ is the slice $psi(V_0 times {h_1})$ in $U_1$. Then $U_1$ is the necessary slice domain for $e$. #qed